dataset: "ivae"
subspace: "iva"
method: "diva"
experiment: "img" # "sim" or "img"
cuda: True

n_epoch: 200
n_modality: 2

# data
eta: [1]
beta: [0.5]
lam: [1] #[1.102657790843584]
latent_dim: 15
n_layer: [2]
n_segment: 8
n_obs_per_seg: [350]
data_seed: 1

# model
misa:
  lr: 0.001
  n_run: 1
  batch_size: 2907

ivae:
  lr: 0.01
  batch_size: 2907
  max_iter_per_epoch: 10

icebeem:
  lr_flow: 0.00001
  lr_ebm: 0.0003
  n_layer_flow: 5
  ebm_hidden_size: 16