dataset: "ivae"
subspace: "iva"
method: "diva"
experiment: "img" # "sim" or "img"

n_epochs: 200
n_modalities: 2

# data
eta: [1]
beta: [0.5]
lam: [1] #[1.102657790843584]
data_dim: 15
n_layers: [2]
n_segments: 8
n_obs_per_seg: [350]
data_seed: 1

# model
misa:
  lr: 0.001
  n_runs: 1
  batch_size: 2907

ivae:
  lr: 0.01
  batch_size: 2907
  cuda: True
  max_iter_per_epoch: 10