dataset: "ivae"
subspace: "iva"
method: "diva"
experiment: "sim" # "sim" or "img"

n_epochs: 200
n_modalities: 2

# data
eta: [1]
beta: [1]
lam: [0.5] #[1.102657790843584]
data_dim: 5
n_layers: [2]
n_segments: 14
n_obs_per_seg: [200]
data_seed: 1

# model
misa:
  lr: 0.001 
  n_runs: 1
  batch_size: 200

ivae:
  lr: 0.01
  batch_size: 140
  cuda: True
  max_iter_per_epoch: 10