dataset: "iva-3x16"
# mask_name: 'ukb2907-smri-aal2'
subspace: "iva" # [2,4]
eta:
beta: 
lambda:
input_dim: 5
output_dim: 6
# data_seed: 1
nRuns: 1

special:
  epochs: 7000
  lr: 0.001
#   cuda: False
