dataset: "iva-3x16"
# mask_name: 'ukb2907-smri-aal2'
subspace: "iva" # [2,4]
eta: [1]
beta: [0.5]
lam: [1]
input_dim: [15, 15, 15]
output_dim: [14, 14, 14]

special:
  nRuns: 1
  epochs: 7000
  batch_size: 1000
  lr: 0.001